// Folders
export const FETCH_FOLDERS_INIT = 'FETCH_FOLDERS_INIT';
export const FETCH_FOLDERS_SUCCESS = 'FETCH_FOLDERS_SUCCESS';
export const FETCH_FOLDERS_FAIL = 'FETCH_FOLDERS_FAIL';
export const CREATE_FOLDER = 'CREATE_FOLDER';
export const CREATE_FOLDER_INIT = 'CREATE_FOLDER_INIT';
export const CREATE_FOLDER_SUCCESS = 'CREATE_FOLDER_SUCCESS';
export const CREATE_FOLDER_FAIL = 'CREATE_FOLDER_FAIL';
export const UPDATE_FOLDER_INIT = 'UPDATE_FOLDER_INIT';
export const UPDATE_FOLDER_SUCCESS = 'UPDATE_FOLDER_SUCCESS';
export const UPDATE_FOLDER_FAIL = 'UPDATE_FOLDER_FAIL';
export const DELETE_FOLDER_INIT = 'DELETE_FOLDER_INIT';
export const DELETE_FOLDER_SUCCESS = 'DELETE_FOLDER_SUCCESS';
export const DELETE_FOLDER_FAIL = 'DELETE_FOLDER_FAIL';
export const SET_SELECTED_FOLDER = 'SET_SELECTED_FOLDER';

// Notes
export const FETCH_NOTES_INIT = 'FETCH_NOTES_INIT';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES_FAIL = 'FETCH_NOTES_FAIL';
export const CREATE_NOTE = 'CREATE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';

export const SET_LAYOUT = 'SET_LAYOUT';

// Loading state
export const LOADING = 'LOADING';
